const states = {
    Afghanistan: [
        "Badakhshan",
        "Badghis",
        "Baghlan",
        "Balkh",
        "Bamyan",
        "Daykundi",
        "Farah",
        "Faryab",
        "Ghazni",
        "Ghor",
        "Helmand",
        "Herat",
        "Jowzjan",
        "Kabul",
        "Kandahar",
        "Kapisa",
        "Khost",
        "Kunar",
        "Kunduz",
        "Laghman",
        "Logar",
        "Nangarhar",
        "Nimroz",
        "Nuristan",
        "Paktia",
        "Paktika",
        "Panjshir",
        "Parwan",
        "Samangan",
        "Sar-e Pol",
        "Takhar",
        "Urozgan",
        "Wardak",
        "Zabul",
    ],
    Albania: [
        "Berat",
        "Dibër",
        "Durrës",
        "Elbasan",
        "Fier",
        "Gjirokastër",
        "Korçë",
        "Kukës",
        "Lezhë",
        "Shkodër",
        "Tiranë",
        "Vlorë",
    ],
    Algeria: [
        "Adrar",
        "Chlef",
        "Laghouat",
        "Oum El Bouaghi",
        "Batna",
        "Béjaïa",
        "Biskra",
        "Béchar",
        "Blida",
        "Bouira",
        "Tamanrasset",
        "Tébessa",
        "Tlemcen",
        "Tiaret",
        "Tizi Ouzou",
        "Alger",
        "Djelfa",
        "Jijel",
        "Sétif",
        "Saïda",
        "Skikda",
        "Sidi Bel Abbès",
        "Annaba",
        "Guelma",
        "Constantine",
        "Médéa",
        "Mostaganem",
        "M'Sila",
        "Mascara",
        "Ouargla",
        "Oran",
        "El Bayadh",
        "Illizi",
        "Bordj Bou Arréridj",
        "Boumerdès",
        "El Tarf",
        "Tindouf",
        "Tissemsilt",
        "El Oued",
        "Khenchela",
        "Souk Ahras",
        "Tipaza",
        "Mila",
        "Aïn Defla",
        "Naâma",
        "Aïn Témouchent",
        "Ghardaïa",
        "Relizane",
    ],
    // Add states for other countries here
};

export default states;
